python steady_script.py > steady01.log  
python steady_script.py > steady02.log  
python steady_script.py > steady03.log  
python steady_script.py > steady04.log  
python steady_script.py > steady05.log  
python steady_script.py > steady06.log  
python steady_script.py > steady07.log  
python steady_script.py > steady08.log  
python steady_script.py > steady09.log  
python steady_script.py > steady10.log  
